"""Confidence scoring for RAG pipeline responses."""

from __future__ import annotations

import re


def score_confidence(
    graph_results: list[dict],
    llm_response: str,
    intent: str,
) -> float:
    """Compute a weighted confidence score for a RAG response.

    Factors:
    - Data completeness (0.4 weight): Were there enough graph results to answer?
    - Citation coverage (0.35 weight): Did the LLM actually cite NODE references?
    - Intent-specific penalty (0.25 weight): Some intents need more evidence.

    Args:
        graph_results: The raw rows returned from Neo4j.
        llm_response: The text generated by the LLM.
        intent: The classified intent (attack_path, coverage_gap, etc.).

    Returns:
        Float between 0.0 and 1.0.
    """
    # --- Data completeness ---
    result_count = len(graph_results)
    if result_count == 0:
        data_score = 0.1
    elif result_count < 3:
        data_score = 0.5
    elif result_count < 10:
        data_score = 0.8
    else:
        data_score = 1.0

    # --- Citation coverage ---
    cited_nodes = set(re.findall(r"\[NODE:(\d+)\]", llm_response))
    available_nodes = set(str(i) for i in range(result_count))

    if not available_nodes:
        citation_score = 0.2
    else:
        citation_ratio = len(cited_nodes & available_nodes) / len(available_nodes)
        citation_score = min(1.0, citation_ratio * 1.5)  # Boost partial citation

    # --- Intent-specific adjustment ---
    # Attack paths need strong evidence chains; general queries are more forgiving.
    intent_multiplier = {
        "attack_path": 0.85,
        "coverage_gap": 0.90,
        "remediation": 0.90,
        "apt_simulation": 0.80,
        "general": 1.0,
    }.get(intent, 0.9)

    raw_score = (
        data_score * 0.40
        + citation_score * 0.35
        + intent_multiplier * 0.25
    )

    return round(min(1.0, max(0.0, raw_score)), 3)
