"""Seed data for the 10 APT persona profiles.

Each persona includes real MITRE ATT&CK group IDs, technique IDs, and sector targeting
based on publicly available threat intelligence.
"""

APT_PERSONAS: list[dict] = [
    {
        "groupId": "G0016",
        "name": "APT29 (Cozy Bear)",
        "origin": "Russia",
        "primarySectors": ["Government", "Diplomatic", "Think Tanks", "Healthcare", "Energy"],
        "motivations": ["Espionage", "Intelligence Collection"],
        "signatureTTPs": [
            {"techniqueId": "T1566.001", "name": "Spearphishing Attachment"},
            {"techniqueId": "T1059.001", "name": "PowerShell"},
            {"techniqueId": "T1071.001", "name": "Web Protocols"},
            {"techniqueId": "T1027", "name": "Obfuscated Files or Information"},
            {"techniqueId": "T1053.005", "name": "Scheduled Task"},
            {"techniqueId": "T1055", "name": "Process Injection"},
            {"techniqueId": "T1078", "name": "Valid Accounts"},
            {"techniqueId": "T1114.002", "name": "Remote Email Collection"},
            {"techniqueId": "T1195.002", "name": "Compromise Software Supply Chain"},
            {"techniqueId": "T1560.001", "name": "Archive via Utility"},
        ],
        "sophistication": "nation-state",
    },
    {
        "groupId": "G0096",
        "name": "APT41 (Double Dragon)",
        "origin": "China",
        "primarySectors": ["Healthcare", "Telecom", "Technology", "Gaming", "Finance"],
        "motivations": ["Espionage", "Financial Gain"],
        "signatureTTPs": [
            {"techniqueId": "T1190", "name": "Exploit Public-Facing Application"},
            {"techniqueId": "T1059.001", "name": "PowerShell"},
            {"techniqueId": "T1059.003", "name": "Windows Command Shell"},
            {"techniqueId": "T1505.003", "name": "Web Shell"},
            {"techniqueId": "T1036.005", "name": "Match Legitimate Name or Location"},
            {"techniqueId": "T1070.004", "name": "File Deletion"},
            {"techniqueId": "T1003.001", "name": "LSASS Memory"},
            {"techniqueId": "T1021.001", "name": "Remote Desktop Protocol"},
            {"techniqueId": "T1195.002", "name": "Compromise Software Supply Chain"},
            {"techniqueId": "T1567.002", "name": "Exfiltration to Cloud Storage"},
        ],
        "sophistication": "nation-state",
    },
    {
        "groupId": "G0032",
        "name": "Lazarus Group",
        "origin": "North Korea",
        "primarySectors": ["Finance", "Cryptocurrency", "Defense", "Entertainment", "Technology"],
        "motivations": ["Financial Gain", "Espionage", "Disruption"],
        "signatureTTPs": [
            {"techniqueId": "T1566.001", "name": "Spearphishing Attachment"},
            {"techniqueId": "T1566.002", "name": "Spearphishing Link"},
            {"techniqueId": "T1059.005", "name": "Visual Basic"},
            {"techniqueId": "T1105", "name": "Ingress Tool Transfer"},
            {"techniqueId": "T1486", "name": "Data Encrypted for Impact"},
            {"techniqueId": "T1565.001", "name": "Stored Data Manipulation"},
            {"techniqueId": "T1071.001", "name": "Web Protocols"},
            {"techniqueId": "T1027.002", "name": "Software Packing"},
            {"techniqueId": "T1055.012", "name": "Process Hollowing"},
            {"techniqueId": "T1489", "name": "Service Stop"},
        ],
        "sophistication": "nation-state",
    },
    {
        "groupId": "G0046",
        "name": "FIN7",
        "origin": "Russia",
        "primarySectors": ["Retail", "Hospitality", "Restaurant", "Finance", "Technology"],
        "motivations": ["Financial Gain"],
        "signatureTTPs": [
            {"techniqueId": "T1566.001", "name": "Spearphishing Attachment"},
            {"techniqueId": "T1059.001", "name": "PowerShell"},
            {"techniqueId": "T1059.005", "name": "Visual Basic"},
            {"techniqueId": "T1053.005", "name": "Scheduled Task"},
            {"techniqueId": "T1547.001", "name": "Registry Run Keys"},
            {"techniqueId": "T1027", "name": "Obfuscated Files or Information"},
            {"techniqueId": "T1005", "name": "Data from Local System"},
            {"techniqueId": "T1041", "name": "Exfiltration Over C2 Channel"},
            {"techniqueId": "T1218.011", "name": "Rundll32"},
            {"techniqueId": "T1036.004", "name": "Masquerade Task or Service"},
        ],
        "sophistication": "advanced",
    },
    {
        "groupId": "G0034",
        "name": "Sandworm Team",
        "origin": "Russia",
        "primarySectors": ["Energy", "Government", "Telecom", "Media", "ICS/SCADA"],
        "motivations": ["Disruption", "Espionage", "Sabotage"],
        "signatureTTPs": [
            {"techniqueId": "T1190", "name": "Exploit Public-Facing Application"},
            {"techniqueId": "T1059.001", "name": "PowerShell"},
            {"techniqueId": "T1059.004", "name": "Unix Shell"},
            {"techniqueId": "T1021.002", "name": "SMB/Windows Admin Shares"},
            {"techniqueId": "T1486", "name": "Data Encrypted for Impact"},
            {"techniqueId": "T1561.002", "name": "Disk Structure Wipe"},
            {"techniqueId": "T1053.005", "name": "Scheduled Task"},
            {"techniqueId": "T1078", "name": "Valid Accounts"},
            {"techniqueId": "T1498", "name": "Network Denial of Service"},
            {"techniqueId": "T1071.001", "name": "Web Protocols"},
        ],
        "sophistication": "nation-state",
    },
    {
        "groupId": "G1015",
        "name": "Scattered Spider",
        "origin": "US/UK",
        "primarySectors": ["Telecom", "Technology", "Finance", "BPO", "Gaming"],
        "motivations": ["Financial Gain", "Data Theft"],
        "signatureTTPs": [
            {"techniqueId": "T1566.004", "name": "Spearphishing Voice"},
            {"techniqueId": "T1621", "name": "Multi-Factor Authentication Request Generation"},
            {"techniqueId": "T1078", "name": "Valid Accounts"},
            {"techniqueId": "T1199", "name": "Trusted Relationship"},
            {"techniqueId": "T1556.006", "name": "Multi-Factor Authentication"},
            {"techniqueId": "T1059.001", "name": "PowerShell"},
            {"techniqueId": "T1003.001", "name": "LSASS Memory"},
            {"techniqueId": "T1567.002", "name": "Exfiltration to Cloud Storage"},
            {"techniqueId": "T1110.001", "name": "Password Guessing"},
            {"techniqueId": "T1539", "name": "Steal Web Session Cookie"},
        ],
        "sophistication": "advanced",
    },
    {
        "groupId": "G1017",
        "name": "Volt Typhoon",
        "origin": "China",
        "primarySectors": ["Critical Infrastructure", "Communications", "Energy", "Water", "Transportation"],
        "motivations": ["Pre-positioning", "Espionage"],
        "signatureTTPs": [
            {"techniqueId": "T1190", "name": "Exploit Public-Facing Application"},
            {"techniqueId": "T1059.001", "name": "PowerShell"},
            {"techniqueId": "T1059.003", "name": "Windows Command Shell"},
            {"techniqueId": "T1218.001", "name": "Compiled HTML File"},
            {"techniqueId": "T1003.003", "name": "NTDS"},
            {"techniqueId": "T1078", "name": "Valid Accounts"},
            {"techniqueId": "T1046", "name": "Network Service Discovery"},
            {"techniqueId": "T1570", "name": "Lateral Tool Transfer"},
            {"techniqueId": "T1071.001", "name": "Web Protocols"},
            {"techniqueId": "T1102", "name": "Web Service"},
        ],
        "sophistication": "nation-state",
    },
    {
        "groupId": "G1006",
        "name": "BlackCat (ALPHV)",
        "origin": "Russia",
        "primarySectors": ["Healthcare", "Finance", "Legal", "Manufacturing", "Technology"],
        "motivations": ["Financial Gain", "Extortion"],
        "signatureTTPs": [
            {"techniqueId": "T1190", "name": "Exploit Public-Facing Application"},
            {"techniqueId": "T1078", "name": "Valid Accounts"},
            {"techniqueId": "T1486", "name": "Data Encrypted for Impact"},
            {"techniqueId": "T1490", "name": "Inhibit System Recovery"},
            {"techniqueId": "T1021.001", "name": "Remote Desktop Protocol"},
            {"techniqueId": "T1059.001", "name": "PowerShell"},
            {"techniqueId": "T1562.001", "name": "Disable or Modify Tools"},
            {"techniqueId": "T1048.003", "name": "Exfiltration Over Unencrypted Non-C2 Protocol"},
            {"techniqueId": "T1003.001", "name": "LSASS Memory"},
            {"techniqueId": "T1069.002", "name": "Domain Groups"},
        ],
        "sophistication": "advanced",
    },
    {
        "groupId": "G0045",
        "name": "Cl0p (TA505)",
        "origin": "Russia",
        "primarySectors": ["Finance", "Healthcare", "Education", "Government", "Retail"],
        "motivations": ["Financial Gain", "Extortion"],
        "signatureTTPs": [
            {"techniqueId": "T1190", "name": "Exploit Public-Facing Application"},
            {"techniqueId": "T1133", "name": "External Remote Services"},
            {"techniqueId": "T1486", "name": "Data Encrypted for Impact"},
            {"techniqueId": "T1490", "name": "Inhibit System Recovery"},
            {"techniqueId": "T1059.001", "name": "PowerShell"},
            {"techniqueId": "T1569.002", "name": "Service Execution"},
            {"techniqueId": "T1070.004", "name": "File Deletion"},
            {"techniqueId": "T1005", "name": "Data from Local System"},
            {"techniqueId": "T1567.002", "name": "Exfiltration to Cloud Storage"},
            {"techniqueId": "T1078", "name": "Valid Accounts"},
        ],
        "sophistication": "advanced",
    },
    {
        "groupId": "UNC3944",
        "name": "UNC3944",
        "origin": "Unknown",
        "primarySectors": ["Telecom", "BPO", "Technology", "Hospitality", "Retail"],
        "motivations": ["Financial Gain", "Data Theft", "SIM Swapping"],
        "signatureTTPs": [
            {"techniqueId": "T1566.004", "name": "Spearphishing Voice"},
            {"techniqueId": "T1078", "name": "Valid Accounts"},
            {"techniqueId": "T1621", "name": "Multi-Factor Authentication Request Generation"},
            {"techniqueId": "T1556.006", "name": "Multi-Factor Authentication"},
            {"techniqueId": "T1136.003", "name": "Cloud Account"},
            {"techniqueId": "T1059.001", "name": "PowerShell"},
            {"techniqueId": "T1021.001", "name": "Remote Desktop Protocol"},
            {"techniqueId": "T1539", "name": "Steal Web Session Cookie"},
            {"techniqueId": "T1567.002", "name": "Exfiltration to Cloud Storage"},
            {"techniqueId": "T1110.001", "name": "Password Guessing"},
        ],
        "sophistication": "advanced",
    },
]
